pipelines:
- name: test0/1
  parameters:
    GitName: JenkinsTest
    Platform: Platform
    globalSystem: Zelgladis
    mono: MQMN6n67
    mvncommand: clean project
    projectver: f3XYi9u9UV
    qqq: mkfkISCmYGVCVCy8
    zxc: '705894'
- name: test0/10
  parameters:
    GitName: JenkinsTest
    Platform: Platform
    globalSystem: Zelgladis
    mono: F8IvJuA3
    mvncommand: clean project
    projectver: ofi3rYlMmt
    qqq: HH7BZL0UBBmpHiAJ
    zxc: '903927'
- name: test0/3
  parameters:
    GitName: JenkinsTest
    Platform: Platform
    globalSystem: Zelgladis
    mono: SiU7qSJv
    mvncommand: clean project
    projectver: zgUetuAFJh
    mvntest: " -pl "
    pom_path: " -pl ''"
- name: test1/4
  parameters:
    GitName: JenkinsTest
    Platform: Platform
    globalSystem: Zelgladis
    mono: bC1uHGJF
    mvncommand: clean project
    projectver: 5ySpaWBVl8
    qqq: ioSumh6JWuKeLYWl
    zxc: '633840'
- name: test1/5
  parameters:
    GitName: JenkinsTest
    Platform: Platform
    globalSystem: Zelgladis
    mono: u7CXRvLM
    mvncommand: clean project
    projectver: 3G5RRzWMdj
    qqq: ZPRFfgLj8oBj3SVV
    zxc: '695518'
- name: test1/6
  parameters:
    GitName: JenkinsTest
    Platform: Platform
    globalSystem: Zelgladis
    mono: 0rc2tvOi
    mvncommand: clean project
    projectver: 91E9un41j5
    qqq: MuUvyKNslyAjNedv
    zxc: '376496'