pipelines:
- name: test0/1
  parameters:
    GitName: uMweww
    Platform: Platform
    globalSystem: globalSystem
    mono: MQMN6n67
    mvncommand: clean project
    projectver: f3XYi9u9UV
    qqq: mkfkISCmYGVCVCy8
    zxc: '705894'
- name: test0/2
  parameters:
    GitName: KvcOgv
    Platform: Platform
    globalSystem: globalSystem
    mono: F8IvJuA3
    mvncommand: clean project
    projectver: ofi3rYlMmt
    qqq: HH7BZL0UBBmpHiAJ
    zxc: '903927'
- name: test0/3
  parameters:
    GitName: 6NcPwj
    Platform: Platform
    globalSystem: globalSystem
    mono: SiU7qSJv
    mvncommand: clean project
    projectver: zgUetuAFJh
    qqq: oVpWBgi4G4s1eMWu
    zxc: '269261'
- name: test1/4
  parameters:
    GitName: XIheNI
    Platform: Platform
    globalSystem: globalSystem
    mono: bC1uHGJF
    mvncommand: clean project
    projectver: 5ySpaWBVl8
    qqq: ioSumh6JWuKeLYWl
    zxc: '633840'
- name: test1/5
  parameters:
    GitName: EyD0rt
    Platform: Platform
    globalSystem: globalSystem
    mono: u7CXRvLM
    mvncommand: clean project
    projectver: 3G5RRzWMdj
    qqq: ZPRFfgLj8oBj3SVV
    zxc: '695518'
- name: test1/6
  parameters:
    GitName: QUq0wP
    Platform: Platform
    globalSystem: globalSystem
    mono: 0rc2tvOi
    mvncommand: clean project
    projectver: 91E9un41j5
    qqq: MuUvyKNslyAjNedv
    zxc: '376496'