pipelines:
- name: dslPipe/test1
  parameters:
    mono: false
    mvncommand: docker mvn
    GitName: cnts-blok-resolver
- name: dslPipe/test2
  parameters:
    CONTOUR: ./inventory/K4/cnts-rqtx-notification-manager
- name: clean_it
  parameters: